// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type PrivateEndpointRegistrationInitParameters struct {

	// Cloud provider of the private endpoint ID
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// Description of the private endpoint
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Region of the private endpoint
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type PrivateEndpointRegistrationObservation struct {

	// Cloud provider of the private endpoint ID
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// Description of the private endpoint
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Region of the private endpoint
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type PrivateEndpointRegistrationParameters struct {

	// Cloud provider of the private endpoint ID
	// +kubebuilder:validation:Optional
	CloudProvider *string `json:"cloudProvider,omitempty" tf:"cloud_provider,omitempty"`

	// Description of the private endpoint
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Region of the private endpoint
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// PrivateEndpointRegistrationSpec defines the desired state of PrivateEndpointRegistration
type PrivateEndpointRegistrationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PrivateEndpointRegistrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrivateEndpointRegistrationInitParameters `json:"initProvider,omitempty"`
}

// PrivateEndpointRegistrationStatus defines the observed state of PrivateEndpointRegistration.
type PrivateEndpointRegistrationStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               PrivateEndpointRegistrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrivateEndpointRegistration is the Schema for the PrivateEndpointRegistrations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,clickhouse}
type PrivateEndpointRegistration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cloudProvider) || (has(self.initProvider) && has(self.initProvider.cloudProvider))",message="spec.forProvider.cloudProvider is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   PrivateEndpointRegistrationSpec   `json:"spec"`
	Status PrivateEndpointRegistrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrivateEndpointRegistrationList contains a list of PrivateEndpointRegistrations
type PrivateEndpointRegistrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivateEndpointRegistration `json:"items"`
}

// Repository type metadata.
var (
	PrivateEndpointRegistration_Kind             = "PrivateEndpointRegistration"
	PrivateEndpointRegistration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrivateEndpointRegistration_Kind}.String()
	PrivateEndpointRegistration_KindAPIVersion   = PrivateEndpointRegistration_Kind + "." + CRDGroupVersion.String()
	PrivateEndpointRegistration_GroupVersionKind = CRDGroupVersion.WithKind(PrivateEndpointRegistration_Kind)
)

func init() {
	SchemeBuilder.Register(&PrivateEndpointRegistration{}, &PrivateEndpointRegistrationList{})
}
