// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CDCInfrastructureInitParameters struct {

	// (Number) CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCPUMillicores *float64 `json:"replicaCpuMillicores,omitempty" tf:"replica_cpu_millicores,omitempty"`

	// (Number) Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb *float64 `json:"replicaMemoryGb,omitempty" tf:"replica_memory_gb,omitempty"`
}

type CDCInfrastructureObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCPUMillicores *float64 `json:"replicaCpuMillicores,omitempty" tf:"replica_cpu_millicores,omitempty"`

	// (Number) Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb *float64 `json:"replicaMemoryGb,omitempty" tf:"replica_memory_gb,omitempty"`
}

type CDCInfrastructureParameters struct {

	// (Number) CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	// +kubebuilder:validation:Optional
	ReplicaCPUMillicores *float64 `json:"replicaCpuMillicores,omitempty" tf:"replica_cpu_millicores,omitempty"`

	// (Number) Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	// +kubebuilder:validation:Optional
	ReplicaMemoryGb *float64 `json:"replicaMemoryGb,omitempty" tf:"replica_memory_gb,omitempty"`
}

// CDCInfrastructureSpec defines the desired state of CDCInfrastructure
type CDCInfrastructureSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CDCInfrastructureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CDCInfrastructureInitParameters `json:"initProvider,omitempty"`
}

// CDCInfrastructureStatus defines the observed state of CDCInfrastructure.
type CDCInfrastructureStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CDCInfrastructureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CDCInfrastructure is the Schema for the CDCInfrastructures API. You can use the clickhouse_clickpipe_cdc_infrastructure resource to manage scaling settings for CDC ClickPipes infrastructure shared across all DB ClickPipes in a service. ~> Important: Only one CDC infrastructure resource per service is supported. Creating multiple instances for the same service will cause conflicts. This endpoint becomes available once at least one DB ClickPipe has been provisioned. The resource will poll for up to 10 minutes waiting for the endpoint to become available. For billing purposes, 2 CPU cores and 8 GB of RAM correspond to one compute unit. ~> Note: CDC infrastructure is shared across all DB ClickPipes and cannot be explicitly deleted. The infrastructure is automatically cleaned up when all DB ClickPipes are deleted.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type CDCInfrastructure struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.replicaCpuMillicores) || (has(self.initProvider) && has(self.initProvider.replicaCpuMillicores))",message="spec.forProvider.replicaCpuMillicores is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.replicaMemoryGb) || (has(self.initProvider) && has(self.initProvider.replicaMemoryGb))",message="spec.forProvider.replicaMemoryGb is a required parameter"
	Spec   CDCInfrastructureSpec   `json:"spec"`
	Status CDCInfrastructureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CDCInfrastructureList contains a list of CDCInfrastructures
type CDCInfrastructureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CDCInfrastructure `json:"items"`
}

// Repository type metadata.
var (
	CDCInfrastructure_Kind             = "CDCInfrastructure"
	CDCInfrastructure_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CDCInfrastructure_Kind}.String()
	CDCInfrastructure_KindAPIVersion   = CDCInfrastructure_Kind + "." + CRDGroupVersion.String()
	CDCInfrastructure_GroupVersionKind = CRDGroupVersion.WithKind(CDCInfrastructure_Kind)
)

func init() {
	SchemeBuilder.Register(&CDCInfrastructure{}, &CDCInfrastructureList{})
}
