// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

// GetCondition of this CDCInfrastructure.
func (mg *CDCInfrastructure) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this CDCInfrastructure.
func (mg *CDCInfrastructure) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this CDCInfrastructure.
func (mg *CDCInfrastructure) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this CDCInfrastructure.
func (mg *CDCInfrastructure) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this CDCInfrastructure.
func (mg *CDCInfrastructure) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this CDCInfrastructure.
func (mg *CDCInfrastructure) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this CDCInfrastructure.
func (mg *CDCInfrastructure) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this CDCInfrastructure.
func (mg *CDCInfrastructure) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this CDCInfrastructure.
func (mg *CDCInfrastructure) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this CDCInfrastructure.
func (mg *CDCInfrastructure) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ClickPipe.
func (mg *ClickPipe) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ClickPipe.
func (mg *ClickPipe) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ClickPipe.
func (mg *ClickPipe) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ClickPipe.
func (mg *ClickPipe) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ClickPipe.
func (mg *ClickPipe) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ClickPipe.
func (mg *ClickPipe) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ClickPipe.
func (mg *ClickPipe) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ClickPipe.
func (mg *ClickPipe) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ClickPipe.
func (mg *ClickPipe) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ClickPipe.
func (mg *ClickPipe) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ReversePrivateEndpoint.
func (mg *ReversePrivateEndpoint) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetCondition of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetDeletionPolicy() xpv2.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetProviderConfigReference() *xpv2.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetWriteConnectionSecretToReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) GetWriteConnectionSecretToReference() *xpv2.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetConditions(c ...xpv2.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetDeletionPolicy(r xpv2.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetManagementPolicies(r xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetProviderConfigReference(r *xpv2.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetWriteConnectionSecretToReference of this ReversePrivateEndpointCustomPrivateDNS.
func (mg *ReversePrivateEndpointCustomPrivateDNS) SetWriteConnectionSecretToReference(r *xpv2.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
