// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type RoleAssignmentInitParameters struct {

	// (Set of String) Set of API key IDs to assign to the role.
	// Set of API key IDs to assign to the role.
	// +listType=set
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// (String) ID of the role to assign actors to.
	// ID of the role to assign actors to.
	// +crossplane:generate:reference:type=github.com/justtrackio/provider-clickhouse/apis/cluster/iam/v1alpha1.Role
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in iam to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v2.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in iam to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v2.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// (Set of String) Set of user IDs to assign to the role.
	// Set of user IDs to assign to the role.
	// +listType=set
	UserIds []*string `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type RoleAssignmentObservation struct {

	// (Set of String) Set of API key IDs to assign to the role.
	// Set of API key IDs to assign to the role.
	// +listType=set
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// (String) Same as role_id.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the role to assign actors to.
	// ID of the role to assign actors to.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (Set of String) Set of user IDs to assign to the role.
	// Set of user IDs to assign to the role.
	// +listType=set
	UserIds []*string `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

type RoleAssignmentParameters struct {

	// (Set of String) Set of API key IDs to assign to the role.
	// Set of API key IDs to assign to the role.
	// +kubebuilder:validation:Optional
	// +listType=set
	APIKeyIds []*string `json:"apiKeyIds,omitempty" tf:"api_key_ids,omitempty"`

	// (String) ID of the role to assign actors to.
	// ID of the role to assign actors to.
	// +crossplane:generate:reference:type=github.com/justtrackio/provider-clickhouse/apis/cluster/iam/v1alpha1.Role
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// Reference to a Role in iam to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDRef *v2.Reference `json:"roleIdRef,omitempty" tf:"-"`

	// Selector for a Role in iam to populate roleId.
	// +kubebuilder:validation:Optional
	RoleIDSelector *v2.Selector `json:"roleIdSelector,omitempty" tf:"-"`

	// (Set of String) Set of user IDs to assign to the role.
	// Set of user IDs to assign to the role.
	// +kubebuilder:validation:Optional
	// +listType=set
	UserIds []*string `json:"userIds,omitempty" tf:"user_ids,omitempty"`
}

// RoleAssignmentSpec defines the desired state of RoleAssignment
type RoleAssignmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   RoleAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleAssignmentInitParameters `json:"initProvider,omitempty"`
}

// RoleAssignmentStatus defines the observed state of RoleAssignment.
type RoleAssignmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               RoleAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoleAssignment is the Schema for the RoleAssignments API. Use the clickhouse_role_assignment resource to assign actors (users and/or API keys) to a role. Works for both system roles and custom roles. One resource manages all actors for a given role. Use user_ids to assign users, api_key_ids to assign API keys, or both. Only one clickhouse_role_assignment per role is needed. ~> Note: On delete, all actors are removed from the role. To look up the ID of a system role by name, use the clickhouse_role data source. To look up a user ID by email, use the clickhouse_user data source. Example Usage
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,clickhouse}
type RoleAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RoleAssignmentSpec   `json:"spec"`
	Status            RoleAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleAssignmentList contains a list of RoleAssignments
type RoleAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleAssignment `json:"items"`
}

// Repository type metadata.
var (
	RoleAssignment_Kind             = "RoleAssignment"
	RoleAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleAssignment_Kind}.String()
	RoleAssignment_KindAPIVersion   = RoleAssignment_Kind + "." + CRDGroupVersion.String()
	RoleAssignment_GroupVersionKind = CRDGroupVersion.WithKind(RoleAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleAssignment{}, &RoleAssignmentList{})
}
