//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigurationInitParameters) DeepCopyInto(out *BackupConfigurationInitParameters) {
	*out = *in
	if in.BackupPeriodInHours != nil {
		in, out := &in.BackupPeriodInHours, &out.BackupPeriodInHours
		*out = new(float64)
		**out = **in
	}
	if in.BackupRetentionPeriodInHours != nil {
		in, out := &in.BackupRetentionPeriodInHours, &out.BackupRetentionPeriodInHours
		*out = new(float64)
		**out = **in
	}
	if in.BackupStartTime != nil {
		in, out := &in.BackupStartTime, &out.BackupStartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigurationInitParameters.
func (in *BackupConfigurationInitParameters) DeepCopy() *BackupConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(BackupConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigurationObservation) DeepCopyInto(out *BackupConfigurationObservation) {
	*out = *in
	if in.BackupPeriodInHours != nil {
		in, out := &in.BackupPeriodInHours, &out.BackupPeriodInHours
		*out = new(float64)
		**out = **in
	}
	if in.BackupRetentionPeriodInHours != nil {
		in, out := &in.BackupRetentionPeriodInHours, &out.BackupRetentionPeriodInHours
		*out = new(float64)
		**out = **in
	}
	if in.BackupStartTime != nil {
		in, out := &in.BackupStartTime, &out.BackupStartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigurationObservation.
func (in *BackupConfigurationObservation) DeepCopy() *BackupConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(BackupConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigurationParameters) DeepCopyInto(out *BackupConfigurationParameters) {
	*out = *in
	if in.BackupPeriodInHours != nil {
		in, out := &in.BackupPeriodInHours, &out.BackupPeriodInHours
		*out = new(float64)
		**out = **in
	}
	if in.BackupRetentionPeriodInHours != nil {
		in, out := &in.BackupRetentionPeriodInHours, &out.BackupRetentionPeriodInHours
		*out = new(float64)
		**out = **in
	}
	if in.BackupStartTime != nil {
		in, out := &in.BackupStartTime, &out.BackupStartTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigurationParameters.
func (in *BackupConfigurationParameters) DeepCopy() *BackupConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(BackupConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseConfigInitParameters) DeepCopyInto(out *BaseConfigInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseConfigInitParameters.
func (in *BaseConfigInitParameters) DeepCopy() *BaseConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(BaseConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseConfigObservation) DeepCopyInto(out *BaseConfigObservation) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseConfigObservation.
func (in *BaseConfigObservation) DeepCopy() *BaseConfigObservation {
	if in == nil {
		return nil
	}
	out := new(BaseConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseConfigParameters) DeepCopyInto(out *BaseConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseConfigParameters.
func (in *BaseConfigParameters) DeepCopy() *BaseConfigParameters {
	if in == nil {
		return nil
	}
	out := new(BaseConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsInitParameters) DeepCopyInto(out *EndpointsInitParameters) {
	*out = *in
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(HTTPSInitParameters)
		**out = **in
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Nativesecure != nil {
		in, out := &in.Nativesecure, &out.Nativesecure
		*out = new(NativesecureInitParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsInitParameters.
func (in *EndpointsInitParameters) DeepCopy() *EndpointsInitParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsObservation) DeepCopyInto(out *EndpointsObservation) {
	*out = *in
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(HTTPSObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Nativesecure != nil {
		in, out := &in.Nativesecure, &out.Nativesecure
		*out = new(NativesecureObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsObservation.
func (in *EndpointsObservation) DeepCopy() *EndpointsObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointsParameters) DeepCopyInto(out *EndpointsParameters) {
	*out = *in
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(HTTPSParameters)
		**out = **in
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Nativesecure != nil {
		in, out := &in.Nativesecure, &out.Nativesecure
		*out = new(NativesecureParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointsParameters.
func (in *EndpointsParameters) DeepCopy() *EndpointsParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntriesInitParameters) DeepCopyInto(out *EntriesInitParameters) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.EndHourUtc != nil {
		in, out := &in.EndHourUtc, &out.EndHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StartHourUtc != nil {
		in, out := &in.StartHourUtc, &out.StartHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.Weekdays != nil {
		in, out := &in.Weekdays, &out.Weekdays
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntriesInitParameters.
func (in *EntriesInitParameters) DeepCopy() *EntriesInitParameters {
	if in == nil {
		return nil
	}
	out := new(EntriesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntriesObservation) DeepCopyInto(out *EntriesObservation) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.EndHourUtc != nil {
		in, out := &in.EndHourUtc, &out.EndHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StartHourUtc != nil {
		in, out := &in.StartHourUtc, &out.StartHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.Weekdays != nil {
		in, out := &in.Weekdays, &out.Weekdays
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntriesObservation.
func (in *EntriesObservation) DeepCopy() *EntriesObservation {
	if in == nil {
		return nil
	}
	out := new(EntriesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntriesParameters) DeepCopyInto(out *EntriesParameters) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.EndHourUtc != nil {
		in, out := &in.EndHourUtc, &out.EndHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StartHourUtc != nil {
		in, out := &in.StartHourUtc, &out.StartHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.Weekdays != nil {
		in, out := &in.Weekdays, &out.Weekdays
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntriesParameters.
func (in *EntriesParameters) DeepCopy() *EntriesParameters {
	if in == nil {
		return nil
	}
	out := new(EntriesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSInitParameters) DeepCopyInto(out *HTTPSInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSInitParameters.
func (in *HTTPSInitParameters) DeepCopy() *HTTPSInitParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPSInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSObservation) DeepCopyInto(out *HTTPSObservation) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSObservation.
func (in *HTTPSObservation) DeepCopy() *HTTPSObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPSObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSParameters) DeepCopyInto(out *HTTPSParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSParameters.
func (in *HTTPSParameters) DeepCopy() *HTTPSParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPSParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAccessInitParameters) DeepCopyInto(out *IPAccessInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAccessInitParameters.
func (in *IPAccessInitParameters) DeepCopy() *IPAccessInitParameters {
	if in == nil {
		return nil
	}
	out := new(IPAccessInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAccessObservation) DeepCopyInto(out *IPAccessObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAccessObservation.
func (in *IPAccessObservation) DeepCopy() *IPAccessObservation {
	if in == nil {
		return nil
	}
	out := new(IPAccessObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAccessParameters) DeepCopyInto(out *IPAccessParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAccessParameters.
func (in *IPAccessParameters) DeepCopy() *IPAccessParameters {
	if in == nil {
		return nil
	}
	out := new(IPAccessParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLInitParameters) DeepCopyInto(out *MySQLInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLInitParameters.
func (in *MySQLInitParameters) DeepCopy() *MySQLInitParameters {
	if in == nil {
		return nil
	}
	out := new(MySQLInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLObservation) DeepCopyInto(out *MySQLObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLObservation.
func (in *MySQLObservation) DeepCopy() *MySQLObservation {
	if in == nil {
		return nil
	}
	out := new(MySQLObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLParameters) DeepCopyInto(out *MySQLParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLParameters.
func (in *MySQLParameters) DeepCopy() *MySQLParameters {
	if in == nil {
		return nil
	}
	out := new(MySQLParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativesecureInitParameters) DeepCopyInto(out *NativesecureInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativesecureInitParameters.
func (in *NativesecureInitParameters) DeepCopy() *NativesecureInitParameters {
	if in == nil {
		return nil
	}
	out := new(NativesecureInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativesecureObservation) DeepCopyInto(out *NativesecureObservation) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativesecureObservation.
func (in *NativesecureObservation) DeepCopy() *NativesecureObservation {
	if in == nil {
		return nil
	}
	out := new(NativesecureObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativesecureParameters) DeepCopyInto(out *NativesecureParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativesecureParameters.
func (in *NativesecureParameters) DeepCopy() *NativesecureParameters {
	if in == nil {
		return nil
	}
	out := new(NativesecureParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointConfigInitParameters) DeepCopyInto(out *PrivateEndpointConfigInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointConfigInitParameters.
func (in *PrivateEndpointConfigInitParameters) DeepCopy() *PrivateEndpointConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointConfigObservation) DeepCopyInto(out *PrivateEndpointConfigObservation) {
	*out = *in
	if in.EndpointServiceID != nil {
		in, out := &in.EndpointServiceID, &out.EndpointServiceID
		*out = new(string)
		**out = **in
	}
	if in.PrivateDNSHostname != nil {
		in, out := &in.PrivateDNSHostname, &out.PrivateDNSHostname
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointConfigObservation.
func (in *PrivateEndpointConfigObservation) DeepCopy() *PrivateEndpointConfigObservation {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointConfigParameters) DeepCopyInto(out *PrivateEndpointConfigParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointConfigParameters.
func (in *PrivateEndpointConfigParameters) DeepCopy() *PrivateEndpointConfigParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistration) DeepCopyInto(out *PrivateEndpointRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistration.
func (in *PrivateEndpointRegistration) DeepCopy() *PrivateEndpointRegistration {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateEndpointRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistrationInitParameters) DeepCopyInto(out *PrivateEndpointRegistrationInitParameters) {
	*out = *in
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistrationInitParameters.
func (in *PrivateEndpointRegistrationInitParameters) DeepCopy() *PrivateEndpointRegistrationInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistrationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistrationList) DeepCopyInto(out *PrivateEndpointRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateEndpointRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistrationList.
func (in *PrivateEndpointRegistrationList) DeepCopy() *PrivateEndpointRegistrationList {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateEndpointRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistrationObservation) DeepCopyInto(out *PrivateEndpointRegistrationObservation) {
	*out = *in
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistrationObservation.
func (in *PrivateEndpointRegistrationObservation) DeepCopy() *PrivateEndpointRegistrationObservation {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistrationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistrationParameters) DeepCopyInto(out *PrivateEndpointRegistrationParameters) {
	*out = *in
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistrationParameters.
func (in *PrivateEndpointRegistrationParameters) DeepCopy() *PrivateEndpointRegistrationParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistrationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistrationSpec) DeepCopyInto(out *PrivateEndpointRegistrationSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistrationSpec.
func (in *PrivateEndpointRegistrationSpec) DeepCopy() *PrivateEndpointRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointRegistrationStatus) DeepCopyInto(out *PrivateEndpointRegistrationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointRegistrationStatus.
func (in *PrivateEndpointRegistrationStatus) DeepCopy() *PrivateEndpointRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachment) DeepCopyInto(out *PrivateEndpointsAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachment.
func (in *PrivateEndpointsAttachment) DeepCopy() *PrivateEndpointsAttachment {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateEndpointsAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentInitParameters) DeepCopyInto(out *PrivateEndpointsAttachmentInitParameters) {
	*out = *in
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PrivateEndpointIdsRefs != nil {
		in, out := &in.PrivateEndpointIdsRefs, &out.PrivateEndpointIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivateEndpointIdsSelector != nil {
		in, out := &in.PrivateEndpointIdsSelector, &out.PrivateEndpointIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentInitParameters.
func (in *PrivateEndpointsAttachmentInitParameters) DeepCopy() *PrivateEndpointsAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentList) DeepCopyInto(out *PrivateEndpointsAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateEndpointsAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentList.
func (in *PrivateEndpointsAttachmentList) DeepCopy() *PrivateEndpointsAttachmentList {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateEndpointsAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentObservation) DeepCopyInto(out *PrivateEndpointsAttachmentObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentObservation.
func (in *PrivateEndpointsAttachmentObservation) DeepCopy() *PrivateEndpointsAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentParameters) DeepCopyInto(out *PrivateEndpointsAttachmentParameters) {
	*out = *in
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PrivateEndpointIdsRefs != nil {
		in, out := &in.PrivateEndpointIdsRefs, &out.PrivateEndpointIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivateEndpointIdsSelector != nil {
		in, out := &in.PrivateEndpointIdsSelector, &out.PrivateEndpointIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentParameters.
func (in *PrivateEndpointsAttachmentParameters) DeepCopy() *PrivateEndpointsAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentSpec) DeepCopyInto(out *PrivateEndpointsAttachmentSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentSpec.
func (in *PrivateEndpointsAttachmentSpec) DeepCopy() *PrivateEndpointsAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateEndpointsAttachmentStatus) DeepCopyInto(out *PrivateEndpointsAttachmentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateEndpointsAttachmentStatus.
func (in *PrivateEndpointsAttachmentStatus) DeepCopy() *PrivateEndpointsAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateEndpointsAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAPIEndpointsInitParameters) DeepCopyInto(out *QueryAPIEndpointsInitParameters) {
	*out = *in
	if in.APIKeyIds != nil {
		in, out := &in.APIKeyIds, &out.APIKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAPIEndpointsInitParameters.
func (in *QueryAPIEndpointsInitParameters) DeepCopy() *QueryAPIEndpointsInitParameters {
	if in == nil {
		return nil
	}
	out := new(QueryAPIEndpointsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAPIEndpointsObservation) DeepCopyInto(out *QueryAPIEndpointsObservation) {
	*out = *in
	if in.APIKeyIds != nil {
		in, out := &in.APIKeyIds, &out.APIKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAPIEndpointsObservation.
func (in *QueryAPIEndpointsObservation) DeepCopy() *QueryAPIEndpointsObservation {
	if in == nil {
		return nil
	}
	out := new(QueryAPIEndpointsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryAPIEndpointsParameters) DeepCopyInto(out *QueryAPIEndpointsParameters) {
	*out = *in
	if in.APIKeyIds != nil {
		in, out := &in.APIKeyIds, &out.APIKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryAPIEndpointsParameters.
func (in *QueryAPIEndpointsParameters) DeepCopy() *QueryAPIEndpointsParameters {
	if in == nil {
		return nil
	}
	out := new(QueryAPIEndpointsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScaling) DeepCopyInto(out *ScheduledScaling) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScaling.
func (in *ScheduledScaling) DeepCopy() *ScheduledScaling {
	if in == nil {
		return nil
	}
	out := new(ScheduledScaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledScaling) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingInitParameters) DeepCopyInto(out *ScheduledScalingInitParameters) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]EntriesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.ServiceIDRef != nil {
		in, out := &in.ServiceIDRef, &out.ServiceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceIDSelector != nil {
		in, out := &in.ServiceIDSelector, &out.ServiceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingInitParameters.
func (in *ScheduledScalingInitParameters) DeepCopy() *ScheduledScalingInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingList) DeepCopyInto(out *ScheduledScalingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScheduledScaling, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingList.
func (in *ScheduledScalingList) DeepCopy() *ScheduledScalingList {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScheduledScalingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingObservation) DeepCopyInto(out *ScheduledScalingObservation) {
	*out = *in
	if in.BaseConfig != nil {
		in, out := &in.BaseConfig, &out.BaseConfig
		*out = new(BaseConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]EntriesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingObservation.
func (in *ScheduledScalingObservation) DeepCopy() *ScheduledScalingObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingParameters) DeepCopyInto(out *ScheduledScalingParameters) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]EntriesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.ServiceIDRef != nil {
		in, out := &in.ServiceIDRef, &out.ServiceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceIDSelector != nil {
		in, out := &in.ServiceIDSelector, &out.ServiceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingParameters.
func (in *ScheduledScalingParameters) DeepCopy() *ScheduledScalingParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingSpec) DeepCopyInto(out *ScheduledScalingSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingSpec.
func (in *ScheduledScalingSpec) DeepCopy() *ScheduledScalingSpec {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledScalingStatus) DeepCopyInto(out *ScheduledScalingStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledScalingStatus.
func (in *ScheduledScalingStatus) DeepCopy() *ScheduledScalingStatus {
	if in == nil {
		return nil
	}
	out := new(ScheduledScalingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Service) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceInitParameters) DeepCopyInto(out *ServiceInitParameters) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.BackupConfiguration != nil {
		in, out := &in.BackupConfiguration, &out.BackupConfiguration
		*out = new(BackupConfigurationInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupID != nil {
		in, out := &in.BackupID, &out.BackupID
		*out = new(string)
		**out = **in
	}
	if in.ByocID != nil {
		in, out := &in.ByocID, &out.ByocID
		*out = new(string)
		**out = **in
	}
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(string)
		**out = **in
	}
	if in.ComplianceType != nil {
		in, out := &in.ComplianceType, &out.ComplianceType
		*out = new(string)
		**out = **in
	}
	if in.DoubleSha1PasswordHashSecretRef != nil {
		in, out := &in.DoubleSha1PasswordHashSecretRef, &out.DoubleSha1PasswordHashSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.EnableCoreDumps != nil {
		in, out := &in.EnableCoreDumps, &out.EnableCoreDumps
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionAssumedRoleIdentifier != nil {
		in, out := &in.EncryptionAssumedRoleIdentifier, &out.EncryptionAssumedRoleIdentifier
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(EndpointsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.IPAccess != nil {
		in, out := &in.IPAccess, &out.IPAccess
		*out = make([]IPAccessInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MaxTotalMemoryGb != nil {
		in, out := &in.MaxTotalMemoryGb, &out.MaxTotalMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinTotalMemoryGb != nil {
		in, out := &in.MinTotalMemoryGb, &out.MinTotalMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NumReplicas != nil {
		in, out := &in.NumReplicas, &out.NumReplicas
		*out = new(float64)
		**out = **in
	}
	if in.PasswordHashSecretRef != nil {
		in, out := &in.PasswordHashSecretRef, &out.PasswordHashSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordWoSecretRef != nil {
		in, out := &in.PasswordWoSecretRef, &out.PasswordWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordWoVersion != nil {
		in, out := &in.PasswordWoVersion, &out.PasswordWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.QueryAPIEndpoints != nil {
		in, out := &in.QueryAPIEndpoints, &out.QueryAPIEndpoints
		*out = new(QueryAPIEndpointsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReleaseChannel != nil {
		in, out := &in.ReleaseChannel, &out.ReleaseChannel
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.TransparentDataEncryption != nil {
		in, out := &in.TransparentDataEncryption, &out.TransparentDataEncryption
		*out = new(TransparentDataEncryptionInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.WarehouseID != nil {
		in, out := &in.WarehouseID, &out.WarehouseID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceInitParameters.
func (in *ServiceInitParameters) DeepCopy() *ServiceInitParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceList) DeepCopyInto(out *ServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceList.
func (in *ServiceList) DeepCopy() *ServiceList {
	if in == nil {
		return nil
	}
	out := new(ServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceObservation) DeepCopyInto(out *ServiceObservation) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.BackupConfiguration != nil {
		in, out := &in.BackupConfiguration, &out.BackupConfiguration
		*out = new(BackupConfigurationObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupID != nil {
		in, out := &in.BackupID, &out.BackupID
		*out = new(string)
		**out = **in
	}
	if in.ByocID != nil {
		in, out := &in.ByocID, &out.ByocID
		*out = new(string)
		**out = **in
	}
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(string)
		**out = **in
	}
	if in.ComplianceType != nil {
		in, out := &in.ComplianceType, &out.ComplianceType
		*out = new(string)
		**out = **in
	}
	if in.EnableCoreDumps != nil {
		in, out := &in.EnableCoreDumps, &out.EnableCoreDumps
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionAssumedRoleIdentifier != nil {
		in, out := &in.EncryptionAssumedRoleIdentifier, &out.EncryptionAssumedRoleIdentifier
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(EndpointsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.IAMRole != nil {
		in, out := &in.IAMRole, &out.IAMRole
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPAccess != nil {
		in, out := &in.IPAccess, &out.IPAccess
		*out = make([]IPAccessObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.IsPrimary != nil {
		in, out := &in.IsPrimary, &out.IsPrimary
		*out = new(bool)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MaxTotalMemoryGb != nil {
		in, out := &in.MaxTotalMemoryGb, &out.MaxTotalMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinTotalMemoryGb != nil {
		in, out := &in.MinTotalMemoryGb, &out.MinTotalMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NumReplicas != nil {
		in, out := &in.NumReplicas, &out.NumReplicas
		*out = new(float64)
		**out = **in
	}
	if in.PasswordWoVersion != nil {
		in, out := &in.PasswordWoVersion, &out.PasswordWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.PrivateEndpointConfig != nil {
		in, out := &in.PrivateEndpointConfig, &out.PrivateEndpointConfig
		*out = new(PrivateEndpointConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.QueryAPIEndpoints != nil {
		in, out := &in.QueryAPIEndpoints, &out.QueryAPIEndpoints
		*out = new(QueryAPIEndpointsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReleaseChannel != nil {
		in, out := &in.ReleaseChannel, &out.ReleaseChannel
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.TransparentDataEncryption != nil {
		in, out := &in.TransparentDataEncryption, &out.TransparentDataEncryption
		*out = new(TransparentDataEncryptionObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.WarehouseID != nil {
		in, out := &in.WarehouseID, &out.WarehouseID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceObservation.
func (in *ServiceObservation) DeepCopy() *ServiceObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceParameters) DeepCopyInto(out *ServiceParameters) {
	*out = *in
	if in.AutoscalingMode != nil {
		in, out := &in.AutoscalingMode, &out.AutoscalingMode
		*out = new(string)
		**out = **in
	}
	if in.BackupConfiguration != nil {
		in, out := &in.BackupConfiguration, &out.BackupConfiguration
		*out = new(BackupConfigurationParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupID != nil {
		in, out := &in.BackupID, &out.BackupID
		*out = new(string)
		**out = **in
	}
	if in.ByocID != nil {
		in, out := &in.ByocID, &out.ByocID
		*out = new(string)
		**out = **in
	}
	if in.CloudProvider != nil {
		in, out := &in.CloudProvider, &out.CloudProvider
		*out = new(string)
		**out = **in
	}
	if in.ComplianceType != nil {
		in, out := &in.ComplianceType, &out.ComplianceType
		*out = new(string)
		**out = **in
	}
	if in.DoubleSha1PasswordHashSecretRef != nil {
		in, out := &in.DoubleSha1PasswordHashSecretRef, &out.DoubleSha1PasswordHashSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.EnableCoreDumps != nil {
		in, out := &in.EnableCoreDumps, &out.EnableCoreDumps
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionAssumedRoleIdentifier != nil {
		in, out := &in.EncryptionAssumedRoleIdentifier, &out.EncryptionAssumedRoleIdentifier
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(EndpointsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.IPAccess != nil {
		in, out := &in.IPAccess, &out.IPAccess
		*out = make([]IPAccessParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IdleScaling != nil {
		in, out := &in.IdleScaling, &out.IdleScaling
		*out = new(bool)
		**out = **in
	}
	if in.IdleTimeoutMinutes != nil {
		in, out := &in.IdleTimeoutMinutes, &out.IdleTimeoutMinutes
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicaMemoryGb != nil {
		in, out := &in.MaxReplicaMemoryGb, &out.MaxReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MaxTotalMemoryGb != nil {
		in, out := &in.MaxTotalMemoryGb, &out.MaxTotalMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicaMemoryGb != nil {
		in, out := &in.MinReplicaMemoryGb, &out.MinReplicaMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(float64)
		**out = **in
	}
	if in.MinTotalMemoryGb != nil {
		in, out := &in.MinTotalMemoryGb, &out.MinTotalMemoryGb
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NumReplicas != nil {
		in, out := &in.NumReplicas, &out.NumReplicas
		*out = new(float64)
		**out = **in
	}
	if in.PasswordHashSecretRef != nil {
		in, out := &in.PasswordHashSecretRef, &out.PasswordHashSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordWoSecretRef != nil {
		in, out := &in.PasswordWoSecretRef, &out.PasswordWoSecretRef
		*out = new(v2.SecretKeySelector)
		**out = **in
	}
	if in.PasswordWoVersion != nil {
		in, out := &in.PasswordWoVersion, &out.PasswordWoVersion
		*out = new(float64)
		**out = **in
	}
	if in.QueryAPIEndpoints != nil {
		in, out := &in.QueryAPIEndpoints, &out.QueryAPIEndpoints
		*out = new(QueryAPIEndpointsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReleaseChannel != nil {
		in, out := &in.ReleaseChannel, &out.ReleaseChannel
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
	if in.TransparentDataEncryption != nil {
		in, out := &in.TransparentDataEncryption, &out.TransparentDataEncryption
		*out = new(TransparentDataEncryptionParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.WarehouseID != nil {
		in, out := &in.WarehouseID, &out.WarehouseID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceParameters.
func (in *ServiceParameters) DeepCopy() *ServiceParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionInitParameters) DeepCopyInto(out *TransparentDataEncryptionInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionInitParameters.
func (in *TransparentDataEncryptionInitParameters) DeepCopy() *TransparentDataEncryptionInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociation) DeepCopyInto(out *TransparentDataEncryptionKeyAssociation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociation.
func (in *TransparentDataEncryptionKeyAssociation) DeepCopy() *TransparentDataEncryptionKeyAssociation {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentDataEncryptionKeyAssociation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationInitParameters) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationInitParameters) {
	*out = *in
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationInitParameters.
func (in *TransparentDataEncryptionKeyAssociationInitParameters) DeepCopy() *TransparentDataEncryptionKeyAssociationInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationList) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransparentDataEncryptionKeyAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationList.
func (in *TransparentDataEncryptionKeyAssociationList) DeepCopy() *TransparentDataEncryptionKeyAssociationList {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransparentDataEncryptionKeyAssociationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationObservation) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationObservation.
func (in *TransparentDataEncryptionKeyAssociationObservation) DeepCopy() *TransparentDataEncryptionKeyAssociationObservation {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationParameters) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationParameters) {
	*out = *in
	if in.KeyID != nil {
		in, out := &in.KeyID, &out.KeyID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationParameters.
func (in *TransparentDataEncryptionKeyAssociationParameters) DeepCopy() *TransparentDataEncryptionKeyAssociationParameters {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationSpec) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationSpec.
func (in *TransparentDataEncryptionKeyAssociationSpec) DeepCopy() *TransparentDataEncryptionKeyAssociationSpec {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionKeyAssociationStatus) DeepCopyInto(out *TransparentDataEncryptionKeyAssociationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionKeyAssociationStatus.
func (in *TransparentDataEncryptionKeyAssociationStatus) DeepCopy() *TransparentDataEncryptionKeyAssociationStatus {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionKeyAssociationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionObservation) DeepCopyInto(out *TransparentDataEncryptionObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RoleID != nil {
		in, out := &in.RoleID, &out.RoleID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionObservation.
func (in *TransparentDataEncryptionObservation) DeepCopy() *TransparentDataEncryptionObservation {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransparentDataEncryptionParameters) DeepCopyInto(out *TransparentDataEncryptionParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransparentDataEncryptionParameters.
func (in *TransparentDataEncryptionParameters) DeepCopy() *TransparentDataEncryptionParameters {
	if in == nil {
		return nil
	}
	out := new(TransparentDataEncryptionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindow) DeepCopyInto(out *UpgradeWindow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindow.
func (in *UpgradeWindow) DeepCopy() *UpgradeWindow {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeWindow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindowInitParameters) DeepCopyInto(out *UpgradeWindowInitParameters) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.ServiceIDRef != nil {
		in, out := &in.ServiceIDRef, &out.ServiceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceIDSelector != nil {
		in, out := &in.ServiceIDSelector, &out.ServiceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.StartHourUtc != nil {
		in, out := &in.StartHourUtc, &out.StartHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.Weekday != nil {
		in, out := &in.Weekday, &out.Weekday
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindowInitParameters.
func (in *UpgradeWindowInitParameters) DeepCopy() *UpgradeWindowInitParameters {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindowInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindowList) DeepCopyInto(out *UpgradeWindowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindowList.
func (in *UpgradeWindowList) DeepCopy() *UpgradeWindowList {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeWindowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindowObservation) DeepCopyInto(out *UpgradeWindowObservation) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.StartHourUtc != nil {
		in, out := &in.StartHourUtc, &out.StartHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.Weekday != nil {
		in, out := &in.Weekday, &out.Weekday
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindowObservation.
func (in *UpgradeWindowObservation) DeepCopy() *UpgradeWindowObservation {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindowParameters) DeepCopyInto(out *UpgradeWindowParameters) {
	*out = *in
	if in.ServiceID != nil {
		in, out := &in.ServiceID, &out.ServiceID
		*out = new(string)
		**out = **in
	}
	if in.ServiceIDRef != nil {
		in, out := &in.ServiceIDRef, &out.ServiceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceIDSelector != nil {
		in, out := &in.ServiceIDSelector, &out.ServiceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.StartHourUtc != nil {
		in, out := &in.StartHourUtc, &out.StartHourUtc
		*out = new(float64)
		**out = **in
	}
	if in.Weekday != nil {
		in, out := &in.Weekday, &out.Weekday
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindowParameters.
func (in *UpgradeWindowParameters) DeepCopy() *UpgradeWindowParameters {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindowSpec) DeepCopyInto(out *UpgradeWindowSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindowSpec.
func (in *UpgradeWindowSpec) DeepCopy() *UpgradeWindowSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeWindowStatus) DeepCopyInto(out *UpgradeWindowStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeWindowStatus.
func (in *UpgradeWindowStatus) DeepCopy() *UpgradeWindowStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeWindowStatus)
	in.DeepCopyInto(out)
	return out
}
