apiVersion: service.clickhouse.justtrack.io/v1alpha1
kind: UpgradeWindow
metadata:
  annotations:
    meta.upbound.io/example-id: service/v1alpha1/upgradewindow
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    startHourUtc: 12
    weekday: 3
